### ISSUE TITLE
Mac OS is Not Properly Showing Up

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#19]
OS values for Mac OS are only showing up as:

10.10
10.11
10.12

**Comment by philbooth** [comment]
We report everything that we get from the user agent string. For example, my current user agent string in Nightly is:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0
```

 I don't think this is actionable.

**Comment by davismtl** [comment]
I'd like to re-open this. I might not have been clear. The whole "Mac OS X" is missing for some of them. Or at least, that's the OS I'm guessing these are...

![screen shot 2017-10-12 at 8 49 49 am](https://user-images.githubusercontent.com/19537086/31505726-606a9fc8-af2a-11e7-9d17-75d7a4ec488b.png)

**Comment by philbooth** [comment]
Oh, my bad. Will take a look.

**Comment by davismtl** [comment]
Note that there are still some showing up as **Mac OS 10.11** so I'm not sure why there is a mix of both.

**Comment by philbooth** [comment]
I notice that the numbers of these are pretty low, the vast majority of OS X users are showing up correctly. You have to scroll quite a way down the full list to find the first one, 10.12:

https://analytics.amplitude.com/org/31251/chart/2yfgbyu

And when I test locally, it's always set correctly. I wonder if these values are arriving via our home-baked [regex for Sync user agents](https://github.com/mozilla/fxa-auth-server/blob/5be347517cf633fe98a374f18d61a021bb864352/lib/userAgent.js#L35), or from `node-uap`. I'm assuming the former but it's hard to be sure.

**Comment by philbooth** [comment]
Tangentially, I wonder if we should avoid reporting `os_version` when we don't have a value for `os_name`:

https://github.com/mozilla/fxa-auth-server/blob/5be347517cf633fe98a374f18d61a021bb864352/lib/metrics/amplitude.js#L177-L178

**Comment by rfk** [comment]
@philbooth in grooming, we're wondering if this is fixed already?

**Comment by philbooth** [comment]
> in grooming, we're wondering if this is fixed already?

Nope, I still see them in Amplitude. Fwiw, I have no concrete plan for a fix yet, other than hoping that #2165 (train 98) makes them go away.

**Comment by philbooth** [comment]
> hoping that mozilla/fxa-auth-server#2165 (train 98) makes them go away.

Just realised that train 98 went out last night. Unfortunately I still see some of these events in today's data, but I'll keep an eye on the chart this week in case that's just the trailing slack from old train 97 events.

**Comment by vbudhram** [comment]
from mtg: closing for now
