### ISSUE TITLE
Add OS to Form Views in Amplitude

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#20]
We don't seem to be passing OS to most form views. This makes breaking down our funnels by OS impossible since it's often the first step.

**Comment by davismtl** [comment]
I'm not sure if it is related but we don't seem to have Country or ua_browser for form views.

**Comment by philbooth** [comment]
> ...we don't seem to have Country...

Opened separately as mozilla/fxa-content-server#5586.
