### ISSUE TITLE
Service Property Values are No Good

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#21]
If you try to filter an event by Service (sync, amo, etc), the values returned are not good. Ultimately, only Sync is readable.

Here is a screenshot of services listed that I can filter on:
<img width="202" alt="image" src="https://user-images.githubusercontent.com/19537086/31471872-ee1fbd5c-ae9f-11e7-9d76-6fb941cf369d.png">

**Comment by philbooth** [comment]
These are supposed to go out in train 97, so the bug is that they are showing up at all. I'll dig in to that but you should see the correct values once train 97 is deployed.

**Comment by philbooth** [comment]
> These are supposed to go out in train 97, so the bug is that they are showing up at all.

My bad, I was thinking of the `fxa_services_used` property, which we have logic for mapping from client id to service name. The `service` property discussed here is of course different, and needs the same logic applied. :man_facepalming:
