### ISSUE TITLE
cert_signed properties

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#22]
Is it possible to pass the OS, Country and all the rest with the cert_signed event?

I know it's server side but it would be nice if we could get those.

**Comment by philbooth** [comment]
@philbooth to triage once he's double-checked the request data

**Comment by philbooth** [comment]
Actually, we're already doing this. There's no event-specific logic around these properties, they're all treated the same. And the request data for these events contains the appropriate data. And I can see the properties on these events when I look for them in Amplitude.

Segmented by OS:
https://analytics.amplitude.com/org/31251/chart/htoe5ft

Segmented by country:
https://analytics.amplitude.com/org/31251/chart/ppv8u5y

@davismtl, I think there's nothing to do here?

**Comment by davismtl** [comment]
You seem to be correct. I know I had problems but I can't recall why. 

I'll close this. Next time I'll make sure to include links to charts to be sure we have something to look at.
