### ISSUE TITLE
Add Newsletter Subscription Status as User Property to fxa_reg - complete

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#23]
I'd like to know what % of users are registering to our newsletter so I can see impact on retention.

I believe we pass SalesForce the subscription after the email is confirmed so I think it makes the most sense to pass it as a user property with "fxa_reg - complete".

I added the property to the taxonomy doc and put it in red until they're available.

**Comment by philbooth** [comment]
@davismtl, slight tweak to your proposal:

In terms of where we have access to the data in the code, the correct event for this property looks like `fxa_reg - email_confirmed`. So that moves it one event earlier in the flow, which I assume you have no problem with but thought I should check first.

**Comment by philbooth** [comment]
Also @davismtl, I wonder whether the choice on this event should be between `subscribed` and just not setting the property at all?

When we set it on `fxa_pref - newsletter` events, the `unsubscribed` value makes sense because the user has definitively taken that action. But here it may not have been a conscious decision, they might just not have noticed the checkbox. What do you reckon?

**Comment by davismtl** [comment]
> In terms of where we have access to the data in the code, the correct event for this property looks like fxa_reg - email_confirmed

This makes sense to me.

>  I wonder whether the choice on this event should be between subscribed and just not setting the property at all?

I'd like to be able to distinguish users who made a clear choice vs those where we just never sent the property to amplitude because they're existing users and we just didn't backfill. Many of our users that have no property are actually subscribed so this would all be very confusing.

So by indicating `unsubscribed` at registration, we're keeping clear records of their known state. Ultimately, the value `not_subscribed` would maybe be more accurate but I don't think we have a need for a 3rd value.
