### ISSUE TITLE
Add email provider to click

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#25]
We don't track the email provider on the click.

**Comment by philbooth** [comment]
There's a few moving parts we'll need to add to the content server for this:

* The `complete_sign_up` and `complete_reset_password` views should parse the email address for well-known domains after reading it from the resume token, using [logic that matches the auth server](https://github.com/mozilla/fxa-auth-server/blob/599476a60b63aaa960f53f3e2c02cf778d4cb56a/lib/email/utils/helpers.js#L198-L210).

* The `/metrics` endpoint should accept an `emailDomain` property.

* `app/scripts/lib/metrics` should be updated to include an `emailDomain` property in the metrics payload if one has been set by the view.

**Comment by vladikoff** [comment]
@davismtl what do we need this for? Seems like we have provider data in later events (bounce, sent)

**Comment by davismtl** [comment]
It is required to measure the click rate by email provider. It is probably one of the best measures for email deliverability.
I don’t recall right now if that is why I wanted it but I filed this when I was trying to make email performance dashboards in Amplitude. It was preventing me from making some charts.
		
		

		Alex Davis // Mountain ViewSr Product Manager // FxA & Sync(415) 769-9247IRC & Slack: adavis
	




On Thu, Jan 11, 2018 at 9:59 AM -0800, "Vlad Filippov" <notifications@github.com> wrote:












@davismtl what do we need this for? Seems like we have provider data in later events (bounce, sent)
