### ISSUE TITLE
Add "entrypoint" to fxa_reg - (complete|created)

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#26]
We can't currently breakdown accounts created or completed by entrypoint.

This is making it difficult to analyze our registration problem that might be related to firstrun.

I've tried to use utm_source as an alternative but the results can vary quite a bit.

**Comment by philbooth** [comment]
As with #25, there are a couple of moving parts to this.

First we'll need to reinstate `entrypoint` to the metrics context payload in the auth server and store it in memcached. Then we can update the content server and the js client to include `entrypoint` in the metrics context payload.

Popping it on the backlog for prioritisation at the next grooming.

Purely as an observeration, it's a mildly frustrating limitation of Amplitude that there's no way to link event properties (between events) without promoting them to user properties. This is a solved problem in our flow metrics. :grin:

**Comment by philbooth** [comment]
> ...it's a mildly frustrating limitation of Amplitude that there's no way to link event properties (between events) without promoting them to user properties.

See also: `ua_browser` and `ua_version`, which we set as user properties but have no earthly business being classified that way, other than to work round this issue.

**Comment by davismtl** [comment]
Sorry for the delay here. 
I'm OK with making this a user property too if you think it makes sense. 
To your point, it might make this less frustrating and a little easier for you.
