### ISSUE TITLE
Device count and login count

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-amplitude-send#30]
Vlad and I got into a weird place here: https://analytics.amplitude.com/org/31251/chart/1rmnrl3

**Comment by vladikoff** [comment]
Additional issue: none VS 0

![image](https://user-images.githubusercontent.com/128755/33030191-af365e44-cde8-11e7-9391-78074941dcac.png)

**Comment by philbooth** [comment]
Regarding the `(none)` bit quickly, again this is because only the auth server sets this property, like https://github.com/mozilla/fxa-amplitude-send/issues/29#issuecomment-345794407. So anyone who drops out of the funnel before reaching the back-end will not have this property set.

**Comment by philbooth** [comment]
Could @ryanfeeleys chart be due to automated test accounts, TPS or whatever? I notice it is counting events, not users.

**Comment by vladikoff** [comment]
Resolved:

First issue was a large number of "people". Those are not people, those are events. Press "Uniques" to see "people"

Second issue was (none). Use `-complete` events that come from the auth server to avoid `none`.
