### ISSUE TITLE
Encode the taxonomy as JSON data

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-amplitude-send#32]
The content and auth servers both contain extensive test coverage for emitting Amplitude events and the various properties. But in light of recent  discussions about weird data artifacts showing up in Amplitude, extensive is insufficient. Because I can't see what happens to data before it reaches FxA (entrypoint, utm params) or what happens to it after (logging 2.0), I want exhaustive, bulletproof tests on which I can base strong claims that FxA is sane. (and if FxA isn't sane, even better because those tests will tell us what's wrong)

However, I don't want to maintain exhaustive test coverage because: a) it's exhausting; b) we're close to the point of minimum viable maintainability in the number of tests as it is and; c) more events and properties are on the way. Instead, if we encode the taxonomy as JSON and also define a schema for trigger events and source properties, we could hack together a kind of domain-specific QuickCheck-esque monkey testing framework.

Ultimately I want to be able to say, with confidence, that events never get dropped after metrics validation occurs on either server, that individual properties never get dropped at all and that invalid events or data are never sent to the logs.

**Comment by vladikoff** [comment]
@philbooth this was triaged into `?` during backlog triage. not sure about the final decision

**Comment by philbooth** [comment]
Strictly speaking it doesn't fit into any of our 2018 categories I don't think. If you want to close it you can, although I still might try to get it done as a Friday project when I have time.

**Comment by philbooth** [comment]
I don't think we're getting to this, closing.
