### ISSUE TITLE
Why are not all desktop users in CA, US, UK seeing SMS form?

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#33]
50% of users confirming their emails at registration on desktop are not seeing the SMS form.

Normally, I'd expect this to be 100%. 

- Are there reasons someone wouldn't see it on desktop at registration?
- Is this a metrics bug?
- A/B test still running?
- Is there a mistake with my chart?

https://analytics.amplitude.com/org/31251/chart/r9mzmof

**Comment by davismtl** [comment]
CC @shane-tomlinson @philbooth @irrationalagent

**Comment by shane-tomlinson** [comment]
@davismtl - Change the "where OS = Linux, ..." to "where ua_browser = Firefox" - the first counts users who verify in Chrome, IE, Safari, etc. Only users who verify in Firefox can send an SMS. It's still a 43% drop, but not quite as bad. I'm trying to dig in but have not developed any valid theories yet.

**Comment by shane-tomlinson** [comment]
A couple more things we don't know in Amplitude:

* How many users are sent to /connect_another_device and /email_verified - those screens aren't reported to amplitude. The sum of connect_another_device, email_verified, and sms should equal the # of users verifying their email in Firefox desktop.
* The reason a user is ineligible to send an SMS - it could be we have something drastically wrong in our selection logic but have no idea. We can get this data in re:dash, but in re:dash we can't limit by country. :/

**Comment by vladikoff** [comment]
@shane-tomlinson can this wait until Q1 ? or do we need to resolve this issue this week?

**Comment by vladikoff** [comment]
from mtg: needs to be verified

**Comment by vladikoff** [comment]
@davismtl is this still a problem?

**Comment by vladikoff** [comment]
@davismtl is this still a problem?

**Comment by davismtl** [comment]
The number is now more like 35% of users aren't seeing it but I think that in some flows, they just won't be able to see it.

Example: register on firstrun > confirm email on phone (won't see sms) > firstrun redirects so new tab so not visible there either.
