### ISSUE TITLE
Does the code process a string char-by-char?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-amplitude-send#34]
I was reading through the code and saw something that didn't seem quite right, @philbooth can you help me walk through it whenever you get a chance?

When we read the input file from S3, we end up calling `s3_object..get()["Body"].read()` here:

  https://github.com/mozilla/fxa-amplitude-send/blob/de521bc47727f44e1167d289c0d5999166cf5c42/amplitude.py#L60

If I understand correctly, the value of the "Body" property is a boto3 `StreamingBody` object, whose `read()` method will return all the data in the body as a string:

  https://botocore.readthedocs.io/en/latest/reference/response.html#botocore.response.StreamingBody

This string ends up being passed into `decompress` here:

  https://github.com/mozilla/fxa-amplitude-send/blob/de521bc47727f44e1167d289c0d5999166cf5c42/amplitude.py#L66

Which iterates over it using `for chunk in data` here:

  https://github.com/mozilla/fxa-amplitude-send/blob/de521bc47727f44e1167d289c0d5999166cf5c42/amplitude.py#L77

If `data` is indeed a single string, this will walk the string character by character, which works but is wildly inefficient.  Am I interpreting things correctly, or does the `read()` above return some sort of chunked iterator rather than a string?

**Comment by philbooth** [comment]
Hmm, I don't think so, although I'm also aware I don't really know what I'm talking about here.

But fwiw:

* We're importing `boto3` and I think the docs you link to are for `boto`. The `boto3` docs are here: http://boto3.readthedocs.io/

* I can't find the relevant bit in those docs but this is binary data, not a string. Not sure what object/iterator that boils down to underneath but I don't think it runs byte-for-byte. If I dump the size of chunk to the console and run it against a bunch of old stage data, I see values like this:

  ```
  523
  669
  273
  318
  127
  299
  166
  122
  325
  577
  ```

  (just to be clear, those are the result of inserting a `print len(chunk)` at line 78 at the top of that loop)

   If I dump chunk itself, obviously I just see incomprehensible grawlix.

* My understanding when I was putting all this together was that I'm iterating over chunks from the stream, whatever size they happen to be as they become available. Admittedly this is not based on the docs themselves, which I didn't find particularly helpful, but instead on [this answer on StackOverflow](https://stackoverflow.com/questions/12571913/python-unzipping-stream-of-bytes/12572031#12572031). I guess that doesn't count much in terms of authority, but at least the approach wasn't completely home-grown.

**Comment by philbooth** [comment]
> I think the docs you link to are for `boto`.

Oh, nope. I see those are the correct docs you linked to sorry, `botocore` is just what `boto3` uses under the hood. I don't where they say it's a string though...

**Comment by rfk** [comment]
I was interpreting this part in the docs for `read()`:

> If the amt argument is omitted, read all data.

As meaning that it returns the data as a single buffer, but I guess I was reading too much into it because...

> If I dump the size of chunk to the console and run it against a bunch of old stage data,
> I see values like this

I can't argue with that in practice :-)

Thanks for double-check this @philbooth!
