### ISSUE TITLE
Audit UTM Parameters

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#44]
In Amplitude, we observed a big change in the utm source properties with Train 104. We finally see big volume for firstrun.

However, we still have half of our login and registrations that don't have a UTM source. Are entrypoints forgetting them? Are we dropping them? Where are these users coming from?

Does Re:Dash have the same problem?

**Comment by philbooth** [comment]
Fwiw, a similar problem is evident in the Redshift numbers:

* [Amplitude](https://analytics.amplitude.com/org/31251/chart/ydv545p)
* [Redshift](https://sql.telemetry.mozilla.org/queries/51434/source#137731)

**Comment by davismtl** [comment]
So, before going crazy debugging our code, I'd propose that we audit various touchpoints/entrypoints and see if we are actually being sent utm params. (e.g. ios, android, desktop settings, mozilla.org, etc...)

If we're not, let's have them added to slowly close the gap.

**Comment by vladikoff** [comment]
from mtg: manual labour investigating the utm params and finding empty utm sources

**Comment by vladikoff** [comment]
from mtg: @davismtl train-110?

**Comment by vladikoff** [comment]
We opened some issues about this in https://github.com/mozilla/fxa-content-server/issues/6757 and https://github.com/mozilla/fxa-content-server/issues/6756 . If we plan to do more let's file actionable issues for those
