### ISSUE TITLE
Device Count Doesn't Seem Accurate

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#48]
I was thinking of a new way to calculate if a user registers and becomes a multi-device user using our existing Amplitude data.

The idea is to make a funnel where registration is the first step and the last step is any event where device_count > 1. Seems simple. 
https://analytics.amplitude.com/org/31251/chart/new/utwpvb3

What I realize is that for many users, we don't seem to have a device count:

https://analytics.amplitude.com/org/31251/chart/new/pg9kb31

I would expect that all registrations have at least 1 device.

If you filter the registration on the sync service or entrypoint firstrun to be sure that users have at least a single device, the numbers end up looking even worst. (I'll file another bug for that one)

**Comment by davismtl** [comment]
CC @irrationalagent

**Comment by philbooth** [comment]
Not sure if I understand the problem correctly, as both the linked charts seem plausible to me?

For the first chart, the conversion to > 1 device doesn't seems about right given our other multi-device numbers. For the second chart, only users who are signed into Sync will have a device record and the difference between the two bars seems about right for that.

What am I missing?

**Comment by vladikoff** [comment]
This was a 2018 bug, can we regroup with a new focused issue in the new year?
