### ISSUE TITLE
Registrations don't always have a service defined

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#49]
We are failing to add a service to each registration:

https://analytics.amplitude.com/org/31251/chart/new/3p7pkxc

Why does this really matter?
FxA should be able to provide reliable registration numbers to its reliers.

If there is a better way to do this, let me know. I just want to make sure we are not too dependent on our reliers passing us UTM parameters for such an important metric.

**Comment by davismtl** [comment]
CC @irrationalagent

**Comment by davismtl** [comment]
I have observed that fxa_reg - created has the service. It just doesn't seem to be on the complete event. Hopefully that's a small fix.

https://analytics.amplitude.com/org/31251/chart/new/03nwbtp

**Comment by vladikoff** [comment]
from mtg: we had the same problem with entrypoint, (complete event), maybe we can use memcache to improve this...
