### ISSUE TITLE
fxa_activity - cert_signed is not associated with user session

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa-amplitude-send#5]
[Example](https://analytics.amplitude.com/org/31251/project/178230/search/31759673987?sessionHandle=V6rFLvI_V6rFL5L_dlGRAy_rg2_b138ccaff2b54fb58cd46d52cee2e0be&eventId=46f6a7c4-9fcd-11e7-a43b-22000a6986e7)

This is because it doesn't have a session_id and the device_id is something different.

**Comment by philbooth** [comment]
@jbuck, this is by design. Is it causing a problem?

**Comment by philbooth** [comment]
And actually, we have no reliable way of associating it with a `session_id` either. I don't think this one is actionable.
