### ISSUE TITLE
Implement `fxa_reg - connect_device` and `fxa_login - connect_device` events

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-amplitude-send#50]
This came up in a meeting with @davismtl just now, we want a single event to cover the different connect-another-device screens/variations, with properties that let us distinguish whether it is SMS or the old screen etc. We should also consider whether it should be two separate events for login and registration of whether one event to cover both would be better. (I'm thinking one event might be best actually)

**Comment by davismtl** [comment]
CC @irrationalagent we had talked about this when we did the SMS analysis.

**Comment by philbooth** [comment]
@davismtl, @irrationalagent, been playing this locally and have a concrete proposal that I want to run by you before opening a PR:

* Replace the `fxa_sms - view` event with `fxa_connect_device - view`, and add a new event property called `connect_device_flow` with a value of `sms`.

* On the old CAD screen, emit `fxa_connect_device - view`, but here set the new property to `cad`.

* Add new `fxa_connect_device - engage` and `fxa_connect_device - submit` events so that we can better track the user's interaction with the form. This event will also have the `connect_device_flow` property set.

Thoughts?

**Comment by philbooth** [comment]
(and note that `fxa_connect_device - submit` will never be emitted from the old CAD screen, because no form submission occurs)

**Comment by davismtl** [comment]
This seems good to me overall. Given that `fxa_connect_device - view` can be seen after confirming email in the new page, in the parent iframe, or potentially as a standalone... I'm wondering if we should add a parameter for context.

> On the old CAD screen, emit fxa_connect_device - view, but here set the new property to cad.

Could we just set the property to `store_buttons` for the default variation?

CC @irrationalagent

**Comment by philbooth** [comment]
> Could we just set the property to `store_buttons` for the default variation?

I can do this, although that variation also has logic that doesn't show any app store buttons, it shows signin links instead. Are we sure we want to use `store_buttons` in that case?

**Comment by philbooth** [comment]
I merged this without getting an answer on the above question, so that it could make train 108. We can make further changes as necessary.

So right now the situation is this:

* For the `engage` event, `connect_device_flow` has 3 possible values:

  * `store_buttons`
  * `signin`
  * `sms`

* But for the `view` event, it still only has 2 possible values:

  * `cad` (covers both the `store_buttons` and `signin` cases above)
  * `sms`

Happy to change it to whatever, it should be possible with some chicanery to make the `view` event match `engage` if we need it to.
