### ISSUE TITLE
Email Clickrate Doesn't Match at All between Amplitude and Re:Dash

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#52]
In Amplitude, we are tracking at nearly half the rate as Re:Dash.

https://analytics.amplitude.com/org/31251/chart/m0j0d4n

(note that if I make it a funnel rather than just divide volume, it gives similar results)

vs

https://sql.telemetry.mozilla.org/queries/4563/source#9187

**Comment by davismtl** [comment]
CC @irrationalagent

**Comment by philbooth** [comment]
Being worked on in #56, closing this one.

**Comment by davismtl** [comment]
@philbooth 

The clickrate being low preceded the recent outage we had. You'll notice in the links above that Amplitude has a clickrate 50% lower than Re:Dash.

**Comment by davismtl** [comment]
Either we re-open this or file a new bug.

**Comment by irrationalagent** [comment]
https://analytics.amplitude.com/org/31251/chart/m0j0d4n/edit/6y6hczb

So I'm pretty confident this has something to do with the amplitude click event specifically. Assuming that the `fxa_reg - email_confirmed` event requires a click on the email, then when you look at the percentages using that event they are similar to re:dash.

**Comment by davismtl** [comment]
Good catch @irrationalagent 

I think the registration comparison is the best because we always send emails whereas for login, some users might not get an email so it's normal that the success rate doesn't match.

That being said, we're looking at a pretty big difference when comparing the `click` to `email_confirmed`: 34% vs 58%
