### ISSUE TITLE
Drop in Email Clickrates

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#53]
Since the release of 59 our email clickrate has dropped substantially.

This may be due to the /whatsnew page so let's see if it goes back to normal on Monday.

https://analytics.amplitude.com/org/31251/chart/m0j0d4n

OR

https://sql.telemetry.mozilla.org/queries/4563#9187

**Comment by davismtl** [comment]
CC @irrationalagent

**Comment by davismtl** [comment]
In Amplitude, it got a lost worst today (see link above).

![Screen Shot 2018-03-17 at 12.04.33 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/577ea18f9a14e11300564d30/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206455f46b7191a379ed0c2b55415c4dbc21254d58eeb9cb74fce36f34985619e8d4640970c76c10ffba8217ba03b8298b4f80b6bbdb1dc7fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e04e54a716376be0713f6e0a.png)

I don't see the same drop on that Re:Dash query though (link above) which give me hope that it's a metrics bug:
![Screen Shot 2018-03-17 at 12.06.10 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/577ea18f9a14e11300564d30/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206455f46b7191a379ed0c2b57415e4ebc21254d58eeb9cb74fce36f34985619e8d4640970c76c10ffba8217ba03b8298b4f80b6bbdb1dc7fa2137a5dad11b61435c52dcbd4f3fb29b4bc259f349e04e54a7153666ee72326e0a.png)

**Comment by irrationalagent** [comment]
My best guess along with #54 and #55 is that forwarding utm params from what's new to amplitude got broken somehow

**Comment by philbooth** [comment]
Being worked on in #56, closing this one.
