### ISSUE TITLE
Can we re-upload all the events for the last few days?

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#56]
JBuck informed me in slack that he identified the cause of our metrics drop.

This leads me to ask, can we re-upload our events for the last few days?

What would be needed?

What's the best way to do that in Amplitude?

**Comment by vladikoff** [comment]
cc @jbuck ?

**Comment by jbuck** [comment]
@philbooth Would it be possible to convert Redash data into Amplitude data? That might get us some missing data back. I'll also look and see if the gollum s3 archives have any extra data.

**Comment by davismtl** [comment]
From Amplitude:
"Provided that you were sending along an insert_id field with all of your events and it is within 7 days of an event being sent we will deduplicate.
Seeing as it happened a couple of days ago we only have a couple of days to play around with."

**Comment by philbooth** [comment]
> Would it be possible to convert Redash data into Amplitude data?

Yes, but it needs a bit of hacking to get us to that point first. That seems like a useful long-term investment anyway though, so I'm more than happy to prioritise it. Digging in to it now...

**Comment by philbooth** [comment]
Note that some events that won't be available from the flow data:

* `fxa_settings - view`
* `fxa_settings - newsletter`
* `fxa_settings - disconnect_device`
* `fxa_email - click`

**Comment by philbooth** [comment]
As per https://github.com/mozilla/fxa-amplitude-send/pull/57#issuecomment-374685154, I don't think there's anything we can do about this. Closing.
