### ISSUE TITLE
Event taxonomy might need some changes

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa-amplitude-send#6]
Right now most of the properties we send to Amplitude are under the `user_properties` key. @davismtl has recommended that we move some of them to Amplitude-standard keys. Specifically:

- `user_properties.ua_browser` should become `os_name`
- `user_properties.ua_version` should become `os_version`
- `user_properties.ua_os` should become `device_model`
- `user_properties.user_country` should become `country`
- `user_properties.user_locale` should become `language`
- `user_properties.user_state`  should become `region`

We'd need to do this in the amplitude function & the auth/content server

My own completely unresearched and unproven suggestion, should we consider changing `flow_id` to become the `session_id`?

**Comment by davismtl** [comment]
@jbuck and I have reviewed his suggestion and made some adjustments and logged them in the taxonomy document in a new tab until @philbooth signs off.

https://docs.google.com/spreadsheets/d/1G_8OJGOxeWXdGJ1Ugmykk33Zsl-qAQL05CONSeD4Uz4/edit#gid=698127172

At which point, I would elect to update the entire taxonomy sheet to reflect these changes.

**Comment by philbooth** [comment]
> My own completely unresearched and unproven suggestion, should we consider changing `flow_id` to become the `session_id`?

Nope, as per [the docs](https://amplitude.zendesk.com/hc/en-us/articles/204771828#optional%C2%A0keys), `session_id` is a timestamp.

**Comment by philbooth** [comment]
Regarding the location-related properties, the justification in the taxonomy for them was:

> Must update Country, City, Region, and DMA with every update if you use Amplitude's properties

@davismtl, was that your comment? Does it imply any special behaviour is required at our end if we switch to using their properties?

**Comment by philbooth** [comment]
> We'd need to do this in the amplitude function & the auth/content server

Fwiw, I'm -1 to adding complexity to the send logic every time there is a spec change. If we really have to do it we'll need a drastically improved testing approach in this repo.

**Comment by philbooth** [comment]
> * `user_properties.ua_os` should become `device_model`

This contradicts the suggestion from the taxonomy document, which is to use `platform`. Do I use `platform` or `device_model`?

**Comment by philbooth** [comment]
> * `user_properties.ua_browser` should become `os_name`
> * `user_properties.ua_version` should become `os_version`
> * `user_properties.ua_os` should become `device_model`

I noted this in the taxonomy doc too but I'm -1 on these. Our current names for them seem more accurate and less confusing to me. What problem are we trying to fix by changing them? Or are we just introducing the potential future problem of confusing people?

**Comment by philbooth** [comment]
What if we changed `user_properties.ua_os` to `os_name` then kept `ua_browser` and `ua_version` in user properties? We could also include `os_version` then, which wasn't in the taxonomy document but seems like it might be useful?
