### ISSUE TITLE
Improve our ability to track multi-device users in Amplitude

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#60]
It was recently brought to my attention that the device ideas in Amplitude may change. This means we don't have a clear idea of the number of devices a user has setup to their account.

We do however have a table in Re:Dash that flags a user as a multi-device user if they have been active on 2 or more devices within the last seven days.

I would like to carry over a similar concept to Amplitude.

Proposal:
We currently have sync_device_count but those numbers are super inflated.

Add a number_active_devices as a user property where the value represents the number of devices we've seen in the last 7 days.

I'm open to other approaches and ideas so let me know.

**Comment by davismtl** [comment]
CC @irrationalagent

**Comment by philbooth** [comment]
> We currently have sync_device_count but those numbers are super inflated.

Actually `sync_device_count` is accurate (or should be). We set it according to how many devices the user has in MySQL. It's only Amplitude's view of devices that is warped, because of the randomly generated `device_id`.

I'm still happy to add the new property if we need it though, just wanted to clarify that point.

**Comment by vladikoff** [comment]
from mtg: use the existing table in redash somehow. 

@philbooth to follow up on this issue

**Comment by philbooth** [comment]
> Actually `sync_device_count` is accurate (or should be).

This was naive of course. We know there'a a fair number of users who are being forced to sign in repeatedly and it seems likely that those users are leaving zombie session tokens / devices behind in the db. See for example this chart:

https://sql.telemetry.mozilla.org/queries/4837#9867
