### ISSUE TITLE
Stopped receiving form view and engage events around 5 pm 2018-04-25

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa-amplitude-send#62]
edit: appears to be affecting content server specifically.

Take a look at this chart, all form views of different types seem to have broke:
https://analytics.amplitude.com/org/31251/chart/3pfr7zz

Same for engage events:
https://analytics.amplitude.com/org/31251/chart/hxp75r4/edit/1wed22f

Now take a look at success metrics (login, reg etc) at the same time, they are OK:
https://analytics.amplitude.com/org/31251/chart/hxp75r4/edit/1wed22f

checking to see re:dash...

**Comment by irrationalagent** [comment]
update: re:dash seems to confirm this is a more general issue than amplitude https://sql.telemetry.mozilla.org/queries/52797/source (data for flow.complete on the 26th but not form views)

**Comment by irrationalagent** [comment]
(note for @davismtl sake, this seems to be a separate issue from https://bugzilla.mozilla.org/show_bug.cgi?id=1457539)

**Comment by irrationalagent** [comment]
jrgm reverted to v1.109.4 and metrics are back. need to figure out what caused breakage in (most likely) v1.110.3 that went out 4/25

**Comment by rfk** [comment]
Thanks for catching this!  Our of curiosity, should we have expected an alert from amplitude here, and/or is this an opportunity to add more alerting for future?

**Comment by irrationalagent** [comment]
@rfk IIUC amplitude alerts aren't an option for us. we'd have to pay extra, I think Alex is lobbying for it. We can do re:dash alerts though, and I should do that. sounds like a good project for next week 👍

**Comment by rfk** [comment]
On the plus side, this definitely showed up as a drop in the daily "FxA: Big Picture (KPIs) dashboard report" email.

**Comment by jrgm** [comment]
I added an alert to one aspect of this that would have been useful to get a pagerduty on. - https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#alarm:alarmFilter=ANY;name=fxa-amplitude-lambda-invokation-errors

**Comment by jrgm** [comment]
And yeah, most of you don't have access to that. But basically, if the Amplitude Lambda task has a high error rate ops will be paged now.

**Comment by rfk** [comment]
IIUC this is resolved
