### ISSUE TITLE
TOTP: Ask to verify a recovery code to complete setup

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#63]
I went through the TOTP flow for Evernotes and in order to complete setup, users had to prove that they had stored their recovery codes by entering of them (which one remain valid).

I think this is a great idea and avoids any slip ups.

It would probably be useful to do this too when a user generates new codes.

<img width="581" alt="screen shot 2018-05-29 at 16 10 57" src="https://user-images.githubusercontent.com/19537086/40690633-adb7c026-635c-11e8-9618-e9fc1c00796a.png">

**Comment by davismtl** [comment]
I did not mean to open it here. 🤦🏼‍♂️
Have a fancy script to move it?
If not, I'll re-open a new one.

**Comment by shane-tomlinson** [comment]
@davismtl - Unfortunately, no magic script that I know of. I'll just move it to the content-server.

**Comment by shane-tomlinson** [comment]
Migrated to mozilla/fxa-content-server#6249

**Comment by vladikoff** [comment]
Dup!
