### ISSUE TITLE
Pass service with cert_signed

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#66]
When looking at DAU using cert_signed (our primary indicator), we can't group or filter on service. Service rare seems defined.:

https://analytics.amplitude.com/mozilla-corp/chart/yswb4kd/edit/rksvzu1

Given that we are signing certificates for Lockbox and Notes, we should probably be able to tell the difference.

**Comment by philbooth** [comment]
@davismtl can you triage this out of backlog if it's more urgent?

**Comment by davismtl** [comment]
Related to: https://github.com/mozilla/fxa-amplitude-send/issues/70

CC @irrationalagent 

This is important because we have two new releases we can't currently track.

**Comment by irrationalagent** [comment]
In combination with https://github.com/mozilla/fxa-amplitude-send/issues/70 this will be important for Lockbox, and as we move towards adding more clients it will be increasingly important. I'd vote for this as a p2

**Comment by philbooth** [comment]
MOVED TO mozilla/fxa-auth-server#2552.
