### ISSUE TITLE
fxa_email - clicked is not associated with session or user

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa-amplitude-send#7]
[Example](https://analytics.amplitude.com/org/31251/project/178230/search/31759821172?sessionHandle=V6rBSjK_V6rBnT4_dlCGl0_rg2_80e634ddec9e4464a00443c43fe3ea32&eventId=064b1108-9fcb-11e7-b037-22000a172f96)

It looks like this has a different session_id & no user_id to associate with. Hm, looks like a different flow_id too? Weird

**Comment by philbooth** [comment]
This will be fixed by persistent device ids, which we're waiting for agreement/approval on. In the meantime, I don't think this is actionable.
