### ISSUE TITLE
Not tracking service for Lockbox and Notes

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#70]
I tried to check the performance of login and registration for Lockbox and Notes but they are not showing up in the "service" property.

See:
https://analytics.amplitude.com/mozilla-corp/chart/llx323e/edit/6kon6zk

I'm guessing the the increase in "undefined_oauth" is Lockbox and Notes.

**Comment by davismtl** [comment]
CC @irrationalagent

**Comment by davismtl** [comment]
Given we also use cert_signed as a proxy for active users, we should make sure those two services are properly showing up there too since IIUC we are signing certificates for them too.

**Comment by davismtl** [comment]
@irrationalagent informs me that this is the hacky chart we made to track:
https://analytics.amplitude.com/mozilla-corp/chart/jdvpv5g

So we have *some* visibility but this is far from ideal.

CC @vladikoff

**Comment by irrationalagent** [comment]
Lockbox has its own way of observing users prior to entering the FxA flow and immediately after (so we can infer how many completed it), but we don't have visibility into the funnel itself, so it would be ideal for us if we could have a service = `Lockbox`. I'd vote for this as a P2 if I had the permissions.

**Comment by philbooth** [comment]
To fix this we need to ask @jrgm to add appropriate client id / service name mappings for Lockbox and Notes to config in the auth and content servers:

* https://github.com/mozilla/fxa-auth-server/blob/35ac5f0d051c6ae472929eb4e4877bdc2a944f32/config/index.js#L564-L569

* https://github.com/mozilla/fxa-content-server/blob/1dc73e323468e3a4d9efabc2facdd1d9c89e1fbf/server/lib/configuration.js#L331-L336

I've added a note about this to the deploy doc for train 117 so hopefully they don't get missed.

**Comment by jrgm** [comment]
@davismtl - in production, I have two clientid entries for Lockbox, and two for Notes (mobile and extension). Shall I put both ids under a single name (2 'lockbox'  id mappings, 2 'notes' id mappings)?

**Comment by davismtl** [comment]
the clientid should just be *Lockbox* or *Notes*
In our metrics, we should be able to sort out mobile vs extension by UA and OS.

**Comment by davismtl** [comment]
lowercase it is. I was just mirroring what you wrote in the comment above me

**Comment by jrgm** [comment]
So @davismtl @irrationalagent - this went live in production, so you should be able to see the effect now. Let me know if it's producing what you want.

**Comment by jrgm** [comment]
Ooops, I overlooked the separate mapping for content, which I've fixed in pending PR https://github.com/mozilla-services/cloudops-deployment/pull/2266

I have one or two patch releases of fxa-content so I pick up that change when that is merged.
