### ISSUE TITLE
fxa_email - sent is malformed and not sent to Amplitude at all

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa-amplitude-send#8]
I get the following error in Lambda logs: `skipping malformed event {u'user_properties': {u'sync_device_count': 0}, u'app_version': u'96', u'event_properties': {u'email_provider': u'other', u'email_type': u'registration'}, u'event_type': u'fxa_email - sent', u'time': 1506107831761} `

If I look at the raw logs, I see that there's no _id properties to associate with: `{"Timestamp":1506107831762000000,"Logger":"fxa-auth-server","Type":"log.amplitudeEvent","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":{"op":"log.amplitudeEvent","data":"{\"time\":1506107831761,\"event_type\":\"fxa_email - sent\",\"event_properties\":{\"email_type\":\"registration\",\"email_provider\":\"other\"},\"user_properties\":{\"sync_device_count\":0},\"app_version\":\"96\"}"}}`

**Comment by philbooth** [comment]
Dup of mozilla/fxa-auth-server#2133.
