### ISSUE TITLE
Registration funnel % down since thu 2019-01-03

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa-amplitude-send#80]
https://analytics.amplitude.com/mozilla-corp/chart/s3z366m seems to be across all entrypoints. No clue what's causing it just yet

**Comment by irrationalagent** [comment]
Looking at all the steps in the funnel, it appears that a large portion of the down-turn is on the first step (view -> engage).

Compare the [last two days](https://analytics.amplitude.com/mozilla-corp/chart/s3z366m/edit/bym8d4d) to the month [ending on jan 2nd](https://analytics.amplitude.com/mozilla-corp/chart/s3z366m/edit/0yezvnk)

**Comment by rfk** [comment]
It looks like there's also a bigger-than-usual dropoff between "submit" and "created" over the past few days.  On the charts you link it's 11.8% dropoff over the past month, vs 18.9% dropoff over the past two days.

**Comment by irrationalagent** [comment]
Yes, true @rfk 

No obvious slowdowns looking [here](https://sql.telemetry.mozilla.org/queries/60800/source#156851)

**Comment by rfk** [comment]
(I had a similar graph over the last four days and the dropoff even larger at 23%)

**Comment by rfk** [comment]
I had a quick look in redash to see if there was an obvious change in the server-side success/failure rate on account creation, but didn't see anything much:

  https://sql.telemetry.mozilla.org/queries/60802

**Comment by irrationalagent** [comment]
since volumes of form views and reg. complete [are basically stable](https://analytics.amplitude.com/mozilla-corp/chart/new/j1m7w8j), I have a feeling there is some metrics funkiness going on rather than breakage

then look at [this](https://analytics.amplitude.com/mozilla-corp/chart/new/nj421wu), `reg - created` events are way up while flow-complete is stable. Makes it look like overall % is down. Not sure why we started counting more of that step all of a sudden.

**Comment by rfk** [comment]
> reg - created events are way up

Is this unique to `entrypoint=firsrun`? If I remove that filter from your graph then it looks pretty stable.

**Comment by irrationalagent** [comment]
Summary of findings so far:

* registration funnel conversion rate down since jan 2nd-3rd [on amplitude](https://analytics.amplitude.com/mozilla-corp/chart/s3z366m/edit/zvfvsyk) but [not on redash](https://sql.telemetry.mozilla.org/queries/60817/source#156901)

* `fxa_reg - complete` as a share of `fxa_reg - view` relatively steady (down a few %) [on amplitude](https://analytics.amplitude.com/mozilla-corp/chart/2nqs55l) but [not on redash](https://sql.telemetry.mozilla.org/queries/60819/source#156907)

* `fxa_reg - created` events as a share of `fxa_reg - submit` events [in amplitude down by double digits](https://analytics.amplitude.com/mozilla-corp/chart/s3z366m/edit/qt5nv5a) but [not on redash](https://sql.telemetry.mozilla.org/queries/60818/source#156904)

* Email sent volume [spiked in amplitude on the 2nd](https://analytics.amplitude.com/mozilla-corp/chart/new/mentint) but [did not spike in redash](https://sql.telemetry.mozilla.org/queries/60816/source#156899)

* weird: android dau [on amplitude down](https://analytics.amplitude.com/mozilla-corp/chart/new/gp85ua6) at same time period but again [not on redshift](https://sql.telemetry.mozilla.org/queries/60820/source#156922)

**Comment by irrationalagent** [comment]
Given that the created and cert signed events are both coming from the auth server, it appears that maybe [some auth server events are not making it to amplitude](https://analytics.amplitude.com/mozilla-corp/chart/new/k0ljyhi) ?

**Comment by irrationalagent** [comment]
Looking at this real-time chart of auth server event volume something happened around 14:00 pdt https://analytics.amplitude.com/mozilla-corp/chart/g42k4hy to my eyes we appear to be intermittently dropping events

**Comment by irrationalagent** [comment]
@jbuck @philbooth @jrgm from irc:

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/5625313/50793990-18f36500-1287-11e9-8c1f-a28cfc38ad49.png">

**Comment by irrationalagent** [comment]
we seem to be receiving a steadier flow of data now. https://analytics.amplitude.com/mozilla-corp/chart/6ekq3qe

**Comment by shane-tomlinson** [comment]
> we seem to be receiving a steadier flow of data now. 

\o/ - thanks for digging in @irrationalagent, @jbuck and @jrgm!

**Comment by shane-tomlinson** [comment]
I'm closing this issue as fixed.
