### ISSUE TITLE
Whitelist for known good events

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa-amplitude-send#9]
Based on issues #5 #7 #8 we'd like to have a whitelist of known good events so that once we've fixed these bugs we only allow good data into Amplitude

**Comment by philbooth** [comment]
Not sure I understand this one. Concretely, which events that we're sending right now wouldn't be in the whitelist?

**Comment by jbuck** [comment]
After discussion with folks, we're not going to do this
